Repository boostcampwm-2024/refactor-web21-TICLE, pull requests merged in 2025-01, with the labels that each got.

#2 [Feat] dockerfile 캐싱을 통한 빌드 시간 단축
  .github/workflows/back-media-cd.yml
  apps/media/.Dockerignore
Labels: ♻️ Refactor, size/s

#4 [Fix] 포트 포워딩 갯수가 많아지면 서버가 터지던 문제 수정
  .github/workflows/back-media-cd.yml
  apps/media/src/main.ts
Labels: BE, 🐞 Bug

#8 [Feat] 모든 참가자의 음성 녹음
  apps/media/src/record/record.service.ts
  apps/media/src/record/recordInfo.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
Labels: BE, ✨ Feature

#10 [Feat] FE 번들링 최적화
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/package.json
  apps/web/src/components/common/Dialog/index.tsx
  apps/web/src/components/common/Header/User.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/StreamView/List/Pinned.tsx
  apps/web/src/components/live/StreamView/List/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/List/UnPinned.tsx
  apps/web/src/components/live/StreamView/List/VideoGrid.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/components/ticle/list/index.tsx
  apps/web/src/components/ticle/open/DateTimePicker.tsx
  apps/web/src/contexts/localStream/context.ts
  apps/web/src/contexts/mediasoup/context.ts
  apps/web/src/contexts/remoteStream/context.ts
  apps/web/src/hooks/mediasoup/useDevice.ts
  apps/web/src/hooks/mediasoup/useLocalStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useProducer.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/mediasoup/useRoom.ts
  apps/web/src/hooks/mediasoup/useTransport.ts
  apps/web/src/hooks/useAudioState.ts
  apps/web/src/hooks/useMediaTracks.ts
  apps/web/src/hooks/usePagination.ts
  apps/web/src/hooks/usePinnedVideo.ts
  apps/web/src/routeTree.gen.ts
  apps/web/src/routes/_authenticated/dashboard/apply.lazy.tsx
  apps/web/src/routes/_authenticated/dashboard/apply.tsx
  apps/web/src/routes/_authenticated/dashboard/open.lazy.tsx
  apps/web/src/routes/_authenticated/dashboard/open.tsx
  apps/web/src/routes/_authenticated/ticle/open.lazy.tsx
  apps/web/src/routes/auth/login.lazy.tsx
  apps/web/src/routes/auth/login.tsx
  apps/web/src/routes/auth/oauth.tsx
  apps/web/src/utils/date.ts
  apps/web/vite.config.ts
  packages/mediasoup/package.json
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/server/index.ts
  packages/mediasoup/src/types.ts
  pnpm-lock.yaml
Labels: ✨ Feature, FE

#11 [Release] 2차 배포 (25.01.23)
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/record/record.service.ts
  apps/media/src/record/recordInfo.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/package.json
  apps/web/src/components/common/Dialog/index.tsx
  apps/web/src/components/common/Header/User.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/StreamView/List/Pinned.tsx
  apps/web/src/components/live/StreamView/List/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/List/UnPinned.tsx
  apps/web/src/components/live/StreamView/List/VideoGrid.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/components/ticle/list/index.tsx
  apps/web/src/components/ticle/open/DateTimePicker.tsx
  apps/web/src/contexts/localStream/context.ts
  apps/web/src/contexts/mediasoup/context.ts
  apps/web/src/contexts/remoteStream/context.ts
  apps/web/src/hooks/mediasoup/useDevice.ts
  apps/web/src/hooks/mediasoup/useLocalStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useProducer.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/mediasoup/useRoom.ts
  apps/web/src/hooks/mediasoup/useTransport.ts
  apps/web/src/hooks/useAudioState.ts
  apps/web/src/hooks/useMediaTracks.ts
  apps/web/src/hooks/usePagination.ts
  apps/web/src/hooks/usePinnedVideo.ts
  apps/web/src/routeTree.gen.ts
  apps/web/src/routes/_authenticated/dashboard/apply.lazy.tsx
  apps/web/src/routes/_authenticated/dashboard/apply.tsx
  apps/web/src/routes/_authenticated/dashboard/open.lazy.tsx
  apps/web/src/routes/_authenticated/dashboard/open.tsx
  apps/web/src/routes/_authenticated/ticle/open.lazy.tsx
  apps/web/src/routes/auth/login.lazy.tsx
  apps/web/src/routes/auth/login.tsx
  apps/web/src/routes/auth/oauth.tsx
  apps/web/src/utils/date.ts
  apps/web/vite.config.ts
  packages/mediasoup/package.json
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/server/index.ts
  packages/mediasoup/src/types.ts
  pnpm-lock.yaml
Labels: 🎉 Release
